== 모임 API

=== 모임 생성

모임을 생성합니다.

operation::group/create[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 상세 조회

모임 상세 정보를 조회합니다.

operation::group/find[snippets='http-request,http-response,path-parameters,response-fields']

=== 모임 검색

모임 목록을 조회합니다.

operation::group/findPageBySearchConditionV2[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 목록 조회(내 학교 더보기)

모임 목록을 조회합니다.

operation::group/findPageByUserUniversity[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 목록 조회(주변 더보기)

모임 목록을 조회합니다.

operation::group/findPageByUserLocation[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 목록 조회(추천 더보기)

모임 목록을 조회합니다.

operation::group/findPageByUserCategories[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 카테고리 목록 조회

모임 카테고리 목록을 조회합니다.

operation::group/findGroupCategories[snippets='http-request,http-response,response-fields']

=== 모임 정보 수정

모임 정보를 수정합니다.

operation::group/updateGroupInformation[snippets='http-request,http-response,request-fields']

=== 모임 대표 이미지 수정

모임 대표 이미지를 수정합니다.

operation::group/updateImage[snippets='http-request,http-response,path-parameters,request-parts,response-fields']

=== 모임 대표 이미지 삭제

모임 대표 이미지를 삭제합니다.

operation::group/deleteImage[snippets='http-request,http-response,path-parameters']

=== 모임장 권한 양도

모임장을 위임합니다.

operation::group/updateManagerByUserId[snippets='http-request,http-response,path-parameters']

=== 모임 종료

모임을 종료합니다.

operation::group/endGroup[snippets='http-request,http-response,path-parameters']

=== 모임 참여 신청

모임 참여 신청합니다.

operation::group/applyParticipantByGroup[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 참여자 목록 조회

모임 참여자 목록을 조회합니다.

operation::group/applyParticipantByGroup[snippets='http-request,http-response,request-parameters,response-fields']

=== 모임 탈퇴

모임을 탈퇴합니다.

operation::group/delete[snippets='http-request,http-response,path-parameters']
